remove initial rm + txt and vrt not overwrite anymore
IGNF/gdalCOG pull request #5
Opened 2023-05-02 12:28 UTC by eluconIGN

2023-05-04 06:53 UTC, leavauchier requested changes
Y avait pas aussi les `rm` dans les tests à modifier ?

2023-05-04 06:53 UTC, leavauchier commented on script/gdal_COG.sh
> -rm $OUTPUT_DIR/$TEMP/*.vrt
Tu gardes pas le fait de supprimer les fichiers txt et vrt finalement ? Maintenant que tu n'as plus besoin de wildcard pour y avoir accès ?

2023-05-04 07:10 UTC, eluconIGN commented
J'avais l'impression que c'était moins grave de laisser du récursif dans les tests. Sinon je peux réécrire les `rm` des tests comme dans le script principal : `rm $PATH/*.txt`

2023-05-04 07:13 UTC, eluconIGN commented on script/gdal_COG.sh
> -rm $OUTPUT_DIR/$TEMP/*.vrt
Ça permet de pouvoir mieux debuger. Mais je peux mettre un nouvel argument `-rm` pour que l'utilisateur puisse choisir ou non de conserver les données intermédiaires (càd les `txt` et `vrt`)

2023-05-04 07:27 UTC, leavauchier commented
Si tu as les paths entiers pour le `rm`, c'est même encore mieux que le `*`. J'ai l'impression que les tests, c'est un endroit où il faut particulièrement faire attention vu qu'on va les jouer sur du code qu'on sera en train de développer, donc plus sujet à des bugs

2023-05-04 15:48 UTC, eluconIGN commented
@leavauchier j'ai fini les modifs.

J'ai séparé en 3 commits : 

- [add long-options + add option remove] dans lequel j'ai ajouté l'option de rm les fichiers intermédiaires, en plus de quoi j'ai ajouté des long-options pour que les paramètres soient plus intelligibles

- [modif test test_docker test_warp + add test_remove] dans lequel j'ai enrichi les tests tout en mettant des chemins directs vers les dossiers/fichiers à supprimer

- [update Readme] dans lequel j'ai mis à jour le readme

2023-05-05 07:53 UTC, leavauchier commented on README.md
> + ATTENTION : Dans l'image Docker, dossiers et fichiers sont créés avec l'utilisateur `root`. Une fois le test avec docker joué, il faut supprimer manuellement tout le dossier `/data/labo` afin de pou
Ca marcherait pas de supprimer directement à partir de l'image docker ? (peut-être uniquement sur option pour pouvoir voir les erreurs en cas d'échec)

2023-05-05 07:53 UTC, leavauchier commented on script/gdal_COG.sh
> +while :
pas mal cette façon de gérer les arguments ! :)

2023-05-05 07:53 UTC, leavauchier commented on script/gdal_COG.sh
> +    echo ERROR : Error in parameters
détail : c'est plus cohérent si tu mets `ERROR : Error in parameters` entre guillemets comme dans la suite

2023-05-05 07:53 UTC, leavauchier commented on script/gdal_COG.sh
> +    rm -f $OUTPUT_DIR/$TEMP/$WARP_FOLDER/*.tif
ligne 97 tu crées des fichiers en `$OUTPUT_DIR/$TEMP/$WARP_FOLDER/*.$EXTENSION` (avec 
`$EXTENSION` en paramètre), donc ici il faudrait supprimer `$OUTPUT_DIR/$TEMP/$WARP_FOLDER/*.$EXTENSION`  plutôt que les `.tif`

2023-05-05 07:53 UTC, leavauchier commented on test_remove.sh
> +    exit 1
j'ai l'impression que le `exit` devrait être dans la première partie du `if`, idem pour les suivants

2023-05-05 10:16 UTC, leavauchier approved these changes

2023-05-05 10:20 UTC, merged